import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <nav className="relative bg-gray-800/50 after:pointer-events-none after:absolute after:inset-x-0 after:bottom-0 after:h-px after:bg-white/10">
          <div className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
            <div className="relative flex h-16 items-center justify-between">


              <div className="absolute inset-y-0 left-0 flex items-center sm:hidden">
                <button className="p-2 text-gray-400">
                  ☰
                </button>
              </div>


              <div className="flex flex-1 items-center justify-center sm:justify-start">
                <div className="flex items-center">
                  <img
                    src="https://tailwindcss.com/plus-assets/img/logos/mark.svg?color=indigo&shade=500"
                    alt="logo"
                    className="h-8"
                  />
                </div>

                <div className="hidden sm:ml-6 sm:flex space-x-4">
                  <Link href="/notes" className="text-gray-300 hover:text-white">
                    Notes
                  </Link>
                  <Link href="/about" className="text-gray-300 hover:text-white">
                    About
                  </Link>
                  <Link href="/contact" className="text-gray-300 hover:text-white">
                    Contact
                  </Link>
                </div>
              </div>


              <div className="flex items-center">
                <img
                  src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e"
                  className="h-8 w-8 rounded-full"
                />
              </div>
            </div>
          </div>
        </nav>


        <main className="flex-1">
          {children}
        </main>


        <footer className="text-center p-4 border-t border-white/10 text-gray-400">
          © Lacroix Nicolas
        </footer>

      </body>
    </html>
  );
}